const data = [
  {
    portId: 19,
    category: "React JS",
    img: "../futsalnormandie.png",
    title: "Futsal Normandie",
    desc: "Site basé uniquement sur la partie intégration en HTML5 / CSS3 / SCSS. Le site est responsive et a été créé avec des animations. Projet Openclassrooms.",
    link: "https://futsalnormandie.fr",
    github: "https://github.com/Romtouf/futsal-articles-hub",
  },
  {
    portId: 20,
    category: "Astro JS",
    img: "../pbernard.webp",
    title: "Pierre Bernard - Massothérapeute",
    desc: "Ce projet a été réalisé pour un client qui souhaite présenter ses services de massothérapie. Le site est créé avec Astro JS, Tailwind CSS et Alpine JS. Site optimisé pour un SEO performant.",
    link: "https://github.com/Romtouf/pierre-bernard",
    github: "https://github.com/Romtouf/pierre-bernard",
  },
  {
    portId: 21,
    category: "IA",
    img: "../simple-meteo-app.png",
    title: "Simple app météo créée avec l'IA",
    desc: "Application météo simple créée avec l'IA. L'application utilise l'API OpenWeatherMap pour obtenir les données météorologiques. L'application a été créée avec React js et l'IA. Le but de ce projet est de découvrir l'IA et son apport sur le développement d'une application.",
    link: "https://simple-test-app-meteo-created-with-ai.netlify.app/",
    github: "https://github.com/Romtouf/Simple-meteo-app-100-AI",
  },
  {
    portId: 22,
    category: "React JS",
    img: "../lcfmanager.png",
    title: "LCF Manager - Gestion d'équipe sportive",
    desc: "Site web créé pour les associations sportives qui souhaitent utiliser un outil leur permettant de gérer de la manière la plus simple et efficace possible leur équipe, avec IA intégrée à disposition. Site développé avec React JS, TypeScript, Supabase. ",
    link: "https://lcfmanager.com/",
    // github: "",
  },
  {
    portId: 23,
    category: "Gestion de projet",
    img: "../qwenta.webp",
    title: "Menu maker by Qwenta",
    desc: "Cette réalisation est basée sur la gestion de projet. Celui-ci a été créé avec une méthode agile, des spécifications techniques, une veille technologique, une solution technique.",
    link: "https://github.com/Romtouf/Menu_Maker_by_Qwenta",
    github: "https://github.com/Romtouf/Menu_Maker_by_Qwenta",
  },
  {
    portId: 24,
    category: "React JS",
    img: "../lcf-live.png",
    title: "LCF Live",
    desc: "LCF Live est un site de gestion des utilisateurs qui auront la possibilité de regarder les matchs en direct de leur équipe préférée et d'interagir via un live chat. Le site est créé avec React js, Node js et Mongo DB.",
    link: "https://lcflive.fr",
    github: "https://github.com/Romtouf/LCFenLive",
  },
];

export default data;
