const data = [
  {
    portId: 19,
    category: "JavaScript",
    img: "assets/portfolio/portfolio1.jpg",
    title: "Project 1",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
  {
    portId: 20,
    category: "React js",
    img: "assets/portfolio/portfolio1.jpg",
    test: "Project 2",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
  {
    portId: 21,
    category: "IA",
    img: "assets/portfolio/portfolio1.jpg",
    title: "Project 3",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
  {
    portId: 22,
    category: "Redux",
    img: "assets/portfolio/portfolio1.jpg",
    title: "Project 4",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
  {
    portId: 23,
    category: "Gestion de projet",
    img: "assets/portfolio/portfolio1.jpg",
    title: "Project 5",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
  {
    portId: 24,
    category: "React js",
    img: "assets/portfolio/portfolio1.jpg",
    title: "Project 6",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    link: "#",
    github: "#",
  },
];

export default data;
